### ISSUE TITLE
Artifact is not available in Maven Central

### ISSUE THREAD

**Issue by bbrudnoy** [avierax/gwt-storage#4]
I attempted to include the dependency via Maven and try the module out as documented:
```
<dependency>
    <groupId>org.gwtproject.storage</groupId>
    <artifactId>gwt-storage</artifactId>
    <version>HEAD-SNAPSHOT</version>
</dependency>
```
Apparently, however, the library isn't available in Maven Central (https://search.maven.org/search?q=org.gwtproject.storage).

**Comment by FrankHossfeld** [comment]
gwt-storage is not released yet. You'll find a SNAPSHOT version here: https://repo.vertispan.com/gwt-snapshot/.

But this version is really old.

**Comment by bbrudnoy** [comment]
@FrankHossfeld Thanks. Is the implication in the`README.md` that the module has to be locally built and installed to be able to include it as a Maven dependency?

**Comment by FrankHossfeld** [comment]
Yes, correct. I think, it is on the list for one of the next releases, but not sure about the state.
 
Questions related to modules are discussed here: https://gitter.im/gwtproject/gwt-modules Feel free to ask your questions inside the room. 

I'll cloes this issue no.
